"""Add Review Model

Revision ID: 32cec02f165a
Revises: b9a3a24a224a
Create Date: 2023-10-01 21:29:16.047338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cec02f165a'
down_revision = 'b9a3a24a224a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
