"""Create Game Model

Revision ID: b9a3a24a224a
Revises: e3ac1fa09c0a
Create Date: 2023-10-01 21:27:52.479032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a3a24a224a'
down_revision = 'e3ac1fa09c0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
